T3_examen/Models/Ejercicios.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace T3_examen.Models
{
    public class Ejercicios
    {

        public int id { get; set; }
        public string nombre { get; set; }
        public string link { get; set; }

    }
}

T3_examen/Controllers/EjerciciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using T3_examen.Models;


namespace T3_examen.Controllers
{
    public class EjerciciosController : Controller
    {

        private EjercicioContext _context;

        public EjerciciosController(EjercicioContext context) {

            this._context = context;
                
        }

        [Authorize]
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.Ejercicios = _context.ejercicios.ToList();

            return View();
        }

        [Authorize]
        public IActionResult CrearRutina()
        {
            return View();
        }

        [Authorize]
        public IActionResult MostrarRutina()
        {

            var claim = HttpContext.User.Claims.FirstOrDefault();

            int idUsuario = _context.usuarios.Where(o => o.usuario == claim.Value).FirstOrDefault().id;
            ViewBag.Rutinas = _context.Rutina.Where(o => o.idUsuario == idUsuario).ToList();

            return View();
        }

        [Authorize]
        public ActionResult DetalleRutina(int idRutina)
        {
            var ejercicios = _context.EjercicioRutina.Include(o => o.ejercicios).Where(o => o.idRutina == idRutina).ToList();
            ViewBag.Ejercicios = ejercicios;
            return View();
        }
    }
}

T3_examen/Views/Ejercicios/CrearRutina.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="text-center">
    <h1>Crear Rutina</h1>
    <br />
    <div class="container">

        <div class="flex-sm-row-reverse" style="border-style:solid; padding: 2%">


            <form action="/Rutina/CrearRutina" method="post">
                <label>Nombre:</label>
                <input type="text" name="nombre" />
                <br />
                <label>Tipo</label>
                <select name="tipo">
                    <option value="Principiante">Principiante</option>
                    <option value="Intermedio">Intermedio</option>
                    <option value="Avanzado">Avanzado</option>
                </select>
                <br /><br />
                <button class="btn-primary" type="submit">Crear</button>
            </form>


        </div>

    </div>

</div>

T3_examen/Views/Ejercicios/DetalleRutina.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Detalle</h1>

<br />

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nº</th>
            <th>Nombre: </th>

            <th>Tiempo</th>

            <th>Video demostrativo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.Ejercicios)
        {
            <tr>
                <td>@item.ejercicios.id</td>
                <td>@item.ejercicios.nombre</td>
                <td>@item.tiempoRutina</td>
                <td>
                    
                    <iframe width="360" height="315"
                            src="@item.ejercicios.link"
                            frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                            gyroscope; picture-in-picture"
                            allowfullscreen>
                    </iframe>

                </td>
            </tr>
        }
    </tbody>
</table>

T3_examen/Views/Ejercicios/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="text-center">
    <h1>EJERCICIOS</h1>

</div>

<div class="container">

    <div class="navbar flex-sm-row-reverse">
        <ul class="flex-grow-1">
            <li class="nav-item">
                <a class="btn btn-info" asp-area="" asp-controller="Ejercicios" asp-action="CrearRutina">Crear Rutina</a>
            </li>
        </ul>
    </div>
    <br />
  


    <h2>Lista de Ejercicios</h2>

    <br />

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nº</th>
                <th>Nombre</th>
                <th>Video</th>
            </tr>
        </thead>
        <tbody>

            @{
                var ejercicios = ((List<Ejercicios>)ViewBag.Ejercicios);
            }

            @for (var i = 0; i < ejercicios.Count; i++)
            {
                var item = ejercicios[i];

                <tr>
                    <td>@item.id</td>
                    <td><b>@item.nombre</b></td>
                    <td>
                        <iframe width="360" height="315"
                                src="@item.link"
                                frameborder="0" allow="accelerometer; autoplay; encrypted-media;
                            gyroscope; picture-in-picture"
                                allowfullscreen>
                        </iframe>
                    </td>
                </tr>

            }
            </tbody>
    </table>
</div>

T3_examen/Views/Ejercicios/MostrarRutina.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (ViewBag.Rutinas.Count != 0)
{
    <table class="table table-bordered">
        <thead>
            <tr>

                <th>Nº</th>
                <th>Nombre</th>
                <th>Tipo</th>
                <th></th>

            </tr>
        </thead>

        <tbody>
            @foreach (var item in ViewBag.Rutinas)
            {
                <tr>
                    <td>@item.id</td>
                    <td>@item.nombreRutina</td>
                    <td>@item.tipoRutina</td>
                    <td>
                        <a href="/Ejercicios/DetalleRutina?idRutina=@item.id">Detalle</a>
                    </td>
                </tr>
            }

        </tbody>
    </table>
}